title: Renan Hipster
author: Renan Franca
description: I enjoy javaâ˜• spring bootğŸƒ and Kubernetesâ˜¸ï¸ to build awesome microservices â€¢ I love implementing automated testsğŸ˜Šâ€¢ @jhipster loverğŸ¤“ # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
# email: "example@mail.com"
twitter_username: renan_afranca
github_username: renanfranca
linkedin_username: renan-af
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#minima:
#  skin: dark
#  social_links:
#    twitter: jekyllrb

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

google_analyticsâ€‹: G-BLB41NFCTQ

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
